### ISSUE TITLE
slack channel: https://1ppm.slack.com

### ISSUE THREAD

**Issue by cityzen** [1ppm/1ppmLog#23]
I've set up this slack channel

**Comment by cityzen** [comment]
bah, no easy way to auto-invite people to slack. for now just respond to this with your email address and I'll add you

**Comment by ranveeraggarwal** [comment]
@1ppm why don't you integrate gitter with this? That would make things a lot easier.

**Comment by 1ppm** [comment]
Added gitter + badge to README. see https://gitter.im/1ppm/challenge - hope it works fine

**Comment by cityzen** [comment]
awesome, that works!

**Comment by 1ppm** [comment]
On second  thought: I've set up a slack channel too - https://1ppmclub.slack.com Github integration is already in place. Early adopters can request access at 1ppm@1ppm.club (Subject: Slack Access)

Reasons: I think Slack is more popular than gitter, so people might already know it or benefit more if they get to know it. Also, on the long run, I don't want this project to become too dependent on the GitHub infrastructure. Maybe there will be a signup with email/password, google etc one day. I don't think 1ppm should be for programming projects exclusively.

There is no *easy* way for auto-invite, but there seems to be a way -> https://github.com/rauchg/slackin I'm working on that now. I know Heroku, but I don't know what this [Now.app](https://zeit.co/app) is about. Any volunteers to check this out?

Hope it will look something like this in the End:

 ![auto-invite](https://cldup.com/IaiPnDEAA6.gif)

**Comment by D-32** [comment]
@1ppm can we decide on either gitter or Slack? Not sure which I should join now...

**Comment by 1ppm** [comment]
@D-32 You are right, having two chats is confusing. Please join Slack - https://1ppmclub.slack.com , send an email to 1ppm@1ppm.club (Subject: "Slack Access") for invitation. (auto-invite will take a while).

**Comment by D-32** [comment]
Perfect, thanks for clarifying :)
