### ISSUE TITLE
API Arquitecture

### ISSUE THREAD

**Issue by jupazave** [1ppm/1ppmLog#77]
It would not be better to use values as '201701' as an attribute instead of using them as keys. The array will be cleaner, and is more natural.

Example
```
{
  "users":
  [
    {
      "username": "aguaviva",
      "githubUrl": "https://github.com/aguaviva",
      "otherUrl": "",
      "projects": [
        {
          "period": "201611",
          "name": "Physics engine",
          "description": "Physics engine, along with a short tutorial on constraints (runs in browser)",
          "status": "",
        }
      {
          "period": "201612",
          "name": "Neural network",
          "description": "Neural network classifier, includes tutorial on backpropagation (runs in browser)",
          "status": ""
        }
      ]
    }
  ]
}

**Comment by ggerhard** [comment]
True. I had the same problem when I was working on the angularJS View. Here is what I came up with:
https://github.com/ggerhard/HallOfFameView/blob/master/app/scripts/controllers/main.js
(see user)
I will talk to @VladimirRubin about a parser update

**Comment by jupazave** [comment]
@ggerhard It would be better to use a date object based on UTC, only setting the month and the year, probably the day for a hangout or something like that.

cc @VladimirRubin

**Comment by ggerhard** [comment]
@jupazave I'd like to provide to views for the beginning: a profile View that contains the users profile data from github and his 1ppm projects ordered by month - maybe 12 tiles or rows with empty spaces for upcoming projects, and a project view that shows all 1ppm projects of the current/selected month

maybe easier to have separate year and month fields?

**Comment by jupazave** [comment]
Made a pull request for the project. https://github.com/VladimirRubin/1ppmHallOfFameParser/pull/1

Maybe, but it would be difficult to order them by date.

**Comment by ggerhard** [comment]
@jupazave nice! that should work for the start. In the next weeks I'd like to migrate this list to a database and extend it with new features (e.g. progress bar, comments, maybe images/screenshots). would be happy to discuss the datamodel if you like.

**Comment by VladimirRubin** [comment]
Hi guys, I'm merged PR with date as attribute fix ;)
